#This allows travis to use caches for pulic repo and use container for deplyment
#See :- https://docs.travis-ci.com/user/workers/standard-infrastructure & https://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

language: node_js

node_js:
  - "0.10"
  - "0.12"
  - "iojs"
  - "4"
  - "6"
